apiVersion: batch/v1
kind: Job
metadata:
  name: mattermost-post-job-success
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: mattermost-success
          image: mattermost:final
          command: [ "python3", "mattermost_api.py"]
          env:
          - name: message
            value: "MESSAGE FROM ARGOCD: The last sync is:  *** Sync OK ***"
          - name: url
            value: "34.61.189.109"
          - name: token
            value: "n148bomritfa7mgt7a4fna9m6w"
          - name: scheme
            value: "http"
          - name: port
            value: "8065"
          - name: channel_name
            value: "Argocd"
          - name: team_name
            value: "IBM"
      restartPolicy: Never
  backoffLimit: 0
